# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "packages/mnn_llm/third_party/**"
    - "build/**"

linter:
  rules:
    # Naming & style.
    - prefer_single_quotes
    - constant_identifier_names
    - non_constant_identifier_names
    # Const constructors where possible.
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    # Code quality.
    - avoid_print
    - avoid_dynamic_calls
    - await_only_futures
    - unawaited_futures
    - unnecessary_null_checks
    - unnecessary_overrides
    - sort_child_properties_last
    - prefer_final_locals
    - use_super_parameters
    - avoid_unnecessary_containers
    - prefer_const_constructors_in_immutables
    - sized_box_for_whitespace